### ISSUE TITLE
Cambiar el nombre de osu!

### ISSUE THREAD

**Issue by rurigk** [AlexAzumi/osu-player-v2#5]
Remueve el nombre de osu! es marca registrada, ppy no tiene problema alguno en este tipo de programas siempre y cuando no usen su marca o logo y haya una leyenda en el cual dejen claro que el programa no tiene relacion con osu! legalmente

**Comment by AlexAzumi** [comment]
Claro, error mío.
Asignaré un nuevo nombre al repositorio y cambiaré los gráficos y/o cualquier otra cosa relacionada con la marca.
